language: objective-c
 
before_install:
  - gem install cocoapods
  - pod install
 
script:
  - xcodebuild -workspace ReDemo.xcworkspace -scheme ReDemo -destination 'platform=iOS Simulator,name=iPhone 6' test
 
after_success:

