language: objective-c
xcode_workspace: ReDemo.xcworkspace
xcode_scheme: ReDemoTests
osx_image: xcode7.2 

 
before_install:
  - gem install cocoapods -v '0.39.0'
  - pod install
 
script:
  - xcodebuild -workspace ReDemo.xcworkspace -scheme ReDemo -destination 'platform=iOS Simulator,name=iPhone 6' test
 
after_success:

